name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The version to release (e.g., '20250414')."
        type: string
      sha:
        description: "The full SHA of the commit to be released (e.g., 'd09ff921d92d6da8d8a608eaa850dc8c0f638194')."
        type: string
      dry-run:
        description: "Dry run? Tests the release process without publishing."
        default: false
        required: false
        type: boolean

env:
  FORCE_COLOR: 1

permissions:
  contents: write
  packages: write
  # Permissions used for actions/attest-build-provenance
  id-token: write
  attestations: write

jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: extractions/setup-just@v2

      # Perform a release in dry-run mode.
      - run: just release-dry-run ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.sha }} ${{ github.event.inputs.tag }}
        if: ${{ github.event.inputs.dry-run == 'true' }}

      # Create the release itself.
      - name: Configure Git identity
        if: ${{ github.event.inputs.dry-run == 'false' }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Fetch the commit so that it exists locally.
      - name: Fetch commit
        if: ${{ github.event.inputs.dry-run == 'false' }}
        run: git fetch origin ${{ github.event.inputs.sha }}

      # Uploading the relevant artifact to the GitHub release.
      - run: just release-run ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.sha }} ${{ github.event.inputs.tag }}
        if: ${{ github.event.inputs.dry-run == 'false' }}

      - run: ls -la dist/*
        if: ${{ github.event.inputs.dry-run == 'false' }}

      - name: Generate attestations
        uses: actions/attest-build-provenance@v2
        if: ${{ github.event.inputs.dry-run == 'false' }}
        with:
          subject-path: |
            dist/*.tar.gz
            dist/*.tar.zst
